### ISSUE TITLE
Feature request: Configurable auto save state

### ISSUE THREAD

**Issue by stefandesu** [rileytestut/Delta#103]
Today, I lost some progress because Delta crashed and I hadn't saved either in-game or with a save state. It was only about 10 or 15 minutes, but I thought that it would be great to configure automatic save state every X minutes. I'd probably just put it on every 1 minute if I could.

(Unfortunately, I can't reproduce the crash. I was playing Pokemon Leaf Green US and it was in the middle of a fight. The second time, the same fight did not cause a crash, and it was the first crash in about 10 hours of gameplay. I compiled and installed Delta from source.)

**Comment by shanegillio** [comment]
Hi! There are a few requests for this, so I'm only closing this as a duplicate
