### ISSUE TITLE
GPGXDeltaCore Dependency Not Public

### ISSUE THREAD

**Issue by bevrist** [rileytestut/Delta#109]
When attempting to clone the submodules of the `develop` branch, the clone fails on the \*__GPGXDeltaCore__\* dependency

the github page for the dependency returns a 404 error so the project looks like its  not publicly available 
https://github.com/rileytestut/GPGXDeltaCore

```bash
Cloning into '/Users/macbook/projects/Delta/Cores/GPGXDeltaCore'...
remote: Repository not found.
fatal: repository 'https://github.com/rileytestut/GPGXDeltaCore.git/' not found
fatal: clone of 'https://github.com/rileytestut/GPGXDeltaCore.git' into submodule path '/Users/macbook/projects/Delta/Cores/GPGXDeltaCore' failed
Failed to clone 'Cores/GPGXDeltaCore' a second time, aborting
```

**Comment by shinshichirou** [comment]
any news here?

**Comment by judge2020** [comment]
Looks like it is public now: https://github.com/rileytestut/GPGXDeltaCore
