### ISSUE TITLE
Getting No such module 'DeltaCore' and 'Harmony'.

### ISSUE THREAD

**Issue by TylerJaacks** [rileytestut/Delta#13]
When I try to build I get No such module 'DeltaCore' and 'Harmony' through out various files in the project. I ran the git submodules and the code is there and Harmony and DeltaCore build fine by themselves.

**Comment by ianclawson** [comment]
I ran into this as well. I was able to get around it by replacing the contents of the base level `.gitmodules` from:

```
[submodule "Cores/DeltaCore"]
	path = Cores/DeltaCore
	url = git@github.com:rileytestut/DeltaCore.git
[submodule "Cores/SNESDeltaCore"]
	path = Cores/SNESDeltaCore
	url = git@github.com:rileytestut/SNESDeltaCore.git
[submodule "External/Roxas"]
	path = External/Roxas
	url = git@github.com:rileytestut/Roxas.git
[submodule "Cores/GBADeltaCore"]
	path = Cores/GBADeltaCore
	url = git@github.com:rileytestut/GBADeltaCore.git
[submodule "Cores/GBCDeltaCore"]
	path = Cores/GBCDeltaCore
	url = git@github.com:rileytestut/GBCDeltaCore.git
[submodule "External/Harmony"]
	path = External/Harmony
	url = https://github.com/rileytestut/Harmony.git
[submodule "Cores/NESDeltaCore"]
	path = Cores/NESDeltaCore
	url = git@github.com:rileytestut/NESDeltaCore.git
[submodule "Cores/N64DeltaCore"]
	path = Cores/N64DeltaCore
	url = git@github.com:rileytestut/N64DeltaCore.git
[submodule "Cores/DSDeltaCore"]
	path = Cores/DSDeltaCore
	url = https://github.com/rileytestut/DSDeltaCore.git

```

to this:

```
[submodule "Cores/DeltaCore"]
	path = Cores/DeltaCore
	url = https://github.com/rileytestut/DeltaCore.git
[submodule "Cores/SNESDeltaCore"]
	path = Cores/SNESDeltaCore
	url = https://github.com/rileytestut/SNESDeltaCore.git
[submodule "External/Roxas"]
	path = External/Roxas
	url = https://github.com/rileytestut/Roxas.git
[submodule "Cores/GBADeltaCore"]
	path = Cores/GBADeltaCore
	url = https://github.com/rileytestut/GBADeltaCore.git
[submodule "Cores/GBCDeltaCore"]
	path = Cores/GBCDeltaCore
	url = https://github.com/rileytestut/GBCDeltaCore.git
[submodule "External/Harmony"]
	path = External/Harmony
	url = https://github.com/rileytestut/Harmony.git
[submodule "Cores/NESDeltaCore"]
	path = Cores/NESDeltaCore
	url = https://github.com/rileytestut/NESDeltaCore.git
[submodule "Cores/N64DeltaCore"]
	path = Cores/N64DeltaCore
	url = https://github.com/rileytestut/N64DeltaCore.git
[submodule "Cores/DSDeltaCore"]
	path = Cores/DSDeltaCore
	url = https://github.com/rileytestut/DSDeltaCore.git

```

Hopefully that works for you! However even after that clears, I'm still seeing the issue referenced here: https://github.com/rileytestut/Delta/issues/9

**Comment by TylerJaacks** [comment]
Did not fix anything for me.

**Comment by ianclawson** [comment]
Oh forgot to say, you’ll need to run `git submodule sync` after updating the file, and then run `git submodule update --init --recursive` 

Hopefully that works for you but I can’t say for sure that it will 🤷‍♂️

**Comment by TylerJaacks** [comment]
Did that and still get this error: Server does not allow request for unadvertised object 4d7ba40073c8fed53fa92f7db07d75b4b8929a41
Fetched in submodule path 'External/Harmony', but it did not contain 4d7ba40073c8fed53fa92f7db07d75b4b8929a41. Direct fetching of that commit failed.

**Comment by fatalite** [comment]
> Did that and still get this error: Server does not allow request for unadvertised object 4d7ba40073c8fed53fa92f7db07d75b4b8929a41
> Fetched in submodule path 'External/Harmony', but it did not contain 4d7ba40073c8fed53fa92f7db07d75b4b8929a41. Direct fetching of that commit failed.

Same here

**Comment by ianclawson** [comment]
That would be the issue referenced in https://github.com/rileytestut/Delta/issues/9

Be sure to follow that for updates, it looks like (if I understand it right) that Riley still needs to push up a few of his local commits to those repos

**Comment by TylerJaacks** [comment]
@ianclawson so there is currently nothing I can do right now?

**Comment by vhqtvn** [comment]
I got it to clone all by cd to each error submodule and do `git checkout master`, only for `External/Harmony` you'll need to run `git submodule update --init --recursive` again inside it.

After that when building you'll get undefined error for `ConflictResolution`, just change all of them to `SyncCoordinator.ConflictResolution` and the corresponding return enum value from `.newest` to `.local` and then it will compile.

Just a temporary workaround until @rileytestut push his updates to Harmony repo.

**Comment by TylerJaacks** [comment]
I still get the "No such module DeltaCore found" error.

**Comment by vhqtvn** [comment]
Try cleaning project and rebuild all from XCode.

**Comment by RG1BB5** [comment]
Are you opening the Delta.xcodeproj file as this can cause the same issue you are having instead open the Delta.xcworkspace file

**Comment by ericlewis** [comment]
This seems resolved, closing for now.
