### ISSUE TITLE
Delta Legal?

### ISSUE THREAD

**Issue by HemilT** [rileytestut/Delta#133]
I have Delta but I don’t want to get sued over emulation of Nintendo.(https://www.tomshardware.com/news/nintendo-emulator-rom-lawsuit-loveretro-loveroms,37489.html)

**Comment by AlexanderNeilson** [comment]
Hi HemilT

I am not a lawyer. 

Emulation itself (depending on your jurisdiction) has often been ruled legal.

That story you reference is from three years ago for a rom site sharing copies of rom files for game’s and using Nintendo’s trademarks. 

Copyright infringement is still illegal in many locations however if you own the cartridges yourself (again depending on local laws) you may have the right to use a rom you have the physical unit of. 

Delta is not likely to be illegal barring some new change is case law or statute. 

If you are not breaching copyright then what could you be sued for. This was a website offering access (distributing) and so Nintendo and other companies are highly likely to go after them. 

Regards
Alexander.

**Comment by HemilT** [comment]
What if I don’t have the cartridges myself?

**Comment by AlexanderNeilson** [comment]
We can’t tell you how you should get access to software. You may be able to find home brew / demo games made for these platforms that are freely available. 

This project is an emulator system that allows you to run software for those systems. Specifically that is what is legal to develop and distribute. 

It is up to the user to supply the software to run in the emulator system and all we can do is encourage people to legally acquire their software as per the laws that apply to them. 

Regards
Alexander

**Comment by HemilT** [comment]
What if I installed the rom from a website like romsgames? Sorry for all questions.

**Comment by AlexanderNeilson** [comment]
Unless your local laws allow for that (highly unlikely) then that would usually be considered copyright infringement.

Your local laws may make a distinction between personal infringement and commercial infringement however if you are concerned about breaking the law it’s likely that this would be breaking the law. 

If you are only worried about if you will have action taken against you then posting this on a public webpage may not be wise to stay under the radar and I cannot and will not encourage you to break the law.

Even if most individual copiers who just download roms and don’t distribute them don’t get sued that doesn’t make it legal it just means they haven’t been found or if located it wasn’t worth the cost for the company to take action on. 

Regards
Alexander

**Comment by lonkle** [comment]
Emulators are a legal grey area but if you own a copy of a game you are allowed a backup of it to use however you like, including on emulators like Delta.
