### ISSUE TITLE
Compiling error: Standard.deltamapping and Standard.deltaskin

### ISSUE THREAD

**Issue by thiagocorreiap** [rileytestut/Delta#136]
I'm trying to compile the project using Xcode following the instructions presented on the readme file. The problem im experiencing is on the last step "Build and Run". When building it gives the following errors.

- error: /Users/user/Developer/Delta/Cores/DSDeltaCore/DSDeltaCore/Standard.deltamapping: No such file or directory (in target 'DSDeltaCore-DSDeltaCore' from project 'Pods')
- error: /Users/user/Developer/Delta/Cores/DSDeltaCore/DSDeltaCore/Controller Skin/Standard.deltaskin: No such file or directory (in target 'DSDeltaCore-DSDeltaCore' from project 'Pods')

**Comment by lonkle** [comment]
Were you able to figure out your build issue @thiagocorreiap?

**Comment by thiagocorreiap** [comment]
Yes, the problem happened after unsuccessfully performing `git submodule update --init --recursive`. I've mentioned the problem that I had with it in this issue #137 .
After solving it, I tried to delete the issue but there was no option available.
