### ISSUE TITLE
.git/config file creating issues on cloning

### ISSUE THREAD

**Issue by thiagocorreiap** [rileytestut/Delta#137]
When using the command `git submodule update --init --recursive` it gives several errors of the type:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I believe it is due to the use of  SSH URL instead of the HTTPS URL. Changing all SSH URLs in the .git/config to HTTPS URL fixed the problem.

**Comment by lonkle** [comment]
You mentioned in this https://github.com/rileytestut/Delta/issues/136#issuecomment-874854442 that you couldn't close this out so I'm going to close this for ya. If I misunderstood, feel free to re-open this.

**Comment by thiagocorreiap** [comment]
Actually I couldn't delete the issue #136 . The problem of this one still persists. I've solved by myself but for anyone else it might happen. Thats why I believe it should be fixed.

**Comment by lonkle** [comment]
What needs to be fixed, you mentioned that changing all SSH links to HTTPS was the solution but our readme only had HTTP links, right?

**Comment by thiagocorreiap** [comment]
So the problem I noticed is on the step 2 of the readme. Before it the `.git/config` file looks like this:
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/rileytestut/Delta.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main

After executing the command `git submodule update --init --recursive` mentioned on the step 2, the `.git/config` file is populated in the following way:
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/rileytestut/Delta.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[submodule "Cores/DSDeltaCore"]
	active = true
	url = https://github.com/rileytestut/DSDeltaCore.git
[submodule "Cores/DeltaCore"]
	active = true
	url = git@github.com:rileytestut/DeltaCore.git
[submodule "Cores/GBADeltaCore"]
	active = true
	url = git@github.com:rileytestut/GBADeltaCore.git
[submodule "Cores/GBCDeltaCore"]
	active = true
	url = git@github.com:rileytestut/GBCDeltaCore.git
[submodule "Cores/GPGXDeltaCore"]
	active = true
	url = https://github.com/rileytestut/GPGXDeltaCore.git
[submodule "Cores/MelonDSDeltaCore"]
	active = true
	url = https://github.com/rileytestut/MelonDSDeltaCore.git
[submodule "Cores/N64DeltaCore"]
	active = true
	url = git@github.com:rileytestut/N64DeltaCore.git
[submodule "Cores/NESDeltaCore"]
	active = true
	url = git@github.com:rileytestut/NESDeltaCore.git
[submodule "Cores/SNESDeltaCore"]
	active = true
	url = git@github.com:rileytestut/SNESDeltaCore.git
[submodule "External/Harmony"]
	active = true
	url = https://github.com/rileytestut/Harmony.git
[submodule "External/Roxas"]
	active = true
	url = git@github.com:rileytestut/Roxas.git

You will notice that in the submodule sections, some of the links are in HTTPS and others are SSH. This is what caused me the trouble I mentioned before.

> When using the command `git submodule update --init --recursive` it gives several errors of the type:
> 
> ```
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> I believe it is due to the use of SSH URL instead of the HTTPS URL. Changing all SSH URLs in the .git/config to HTTPS URL fixed the problem.

I'm not sure how could this be fixed but what I did was to manually modify each link to HTTPS and copy them. After, erase the entire project and clone again. This time, paste the correct links on the `.git/config` file and then run the command `git submodule update --init --recursive`. That what got my finally work.

**Comment by lonkle** [comment]
Maybe `perl -i -p -e 's|git@(.*?)/|https://\1:|g' .gitmodules` could be written after that command to fix the file before moving onto the next step?

But, it looks the sub-repo decides the type of URL to put in the config because it's different for each. I'll look into it, thanks for telling me your solution! ☺️
