### ISSUE TITLE
Basic tvOS Support

### ISSUE THREAD

**Issue by justandhans** [rileytestut/Delta#143]
I'm fine with just Google Sync and local multiplayer. Everything else doesn't matter.
Can you provide an ETA or a way to donate to speed up the development of a tvOS version.

**Comment by lonkle** [comment]
It’s coming. You can donate here. https://bit.ly/rileytestut-patreon

**Comment by justandhans** [comment]
Is there a rough date for release being considered?

Sincerely,
Justin Hansen
