### ISSUE TITLE
iPad resolution support.

### ISSUE THREAD

**Issue by GittyMac** [rileytestut/Delta#16]
Delta does not support the iPad resolution, which leads to the iPhone letterbox, with a smaller keyboard and resolution.

**Comment by BSBussell** [comment]
Riley Has tweeted about this [Here](https://twitter.com/rileytestut/status/1178751520822591488?s=21) so it should be added soon

**Comment by ericlewis** [comment]
Duplicate

**Comment by apple-ihack-geek** [comment]
Didn't age well :/

**Comment by RestartB** [comment]
Any progress on this?

**Comment by BigCammyC** [comment]
still waiting lol
