### ISSUE TITLE
Resuming the game after creating a save state freezes the emulator

### ISSUE THREAD

**Issue by CooperCorona** [rileytestut/Delta#182]
Often, after opening the menu and creating a save state, the emulator is frozen. I can't restart it without loading a save state (restarting the game would lose my progress). Usually, I can reload the save state that I just created, but sometimes the save state is itself corrupted. The buttons all respond to my touches (I feel the haptic feedback). It seems like the emulator simply isn't running? My steps are

* Open the menu
* Open the save state list
* Create a save state
* Dismiss the menu
* The emulator is now frozen.

Reopening the menu or save state list does not fix it. I'm playing a Pokemon Crystal hack on the GBC emulator. My device is an iPhone 11 running iOS 15.4.1. Delta version is 1.3.1.

**Comment by CooperCorona** [comment]
Ok, I think I know what is causing it. It _always_ occurs if I tap on any save state other than the one I've created. It _never_ occurs as long as I don't touch any of the other save states. When I touch a save state (or rather, long press), it previews the game. So I imagine Delta is running the emulator with that other save state, stopping when you dismiss the preview, but then the original ROM in memory is now lost? So dismissing the menu can't restart the ROM because the actively running one is now gone, replaced by the preview which was deactivated.

**Comment by sg3510** [comment]
I still seem to be having this issue for gbc emulator plus i lose save states as a result
