### ISSUE TITLE
Nintendo DS controller skin missing and touch screen inoperative

### ISSUE THREAD

**Issue by johncoxon** [rileytestut/Delta#186]
I've compiled and run the `develop` branch on an iPad, and I'm seeing issues with the Nintendo DS support,

1. When I run the app I get an error in the Xcode console: `Failed to update default skin for system: ds` and the Nintendo DS controller skin doesn't appear – I've tried downloading alternates and adding those, but they don't work.
2. The touch screen is unresponsive. This may be related to #28 as when I first ran the DS emulator I had a DS4 controller attached, but even since turning it off the touch screen is not responsive (I've tried force quitting Delta, restarting my iPad, etc – no dice).

**Comment by icelaglace** [comment]
Issue 1 is quite simple, actually.

It seems GitHub messed up the transfer of the MelonDSCore's iPad PNG files.
So the Standard.deltaskin is actually a few bytes.

Replace the data with the correct files then you're good to go :)

**Comment by johncoxon** [comment]
Thanks for this – I replaced the invalid files (the iPad PNGs were also corrupt) and that did the trick.
