### ISSUE TITLE
Feature for removing controllers in settings

### ISSUE THREAD

**Issue by kibabyte** [rileytestut/Delta#190]
Due to me connecting a 3rd party controller via ncontrol, every time i launch Delta it reverts back to this (disconnected and forgotten) controller. A button for removing these or a workaround maybe involving the application files would be highly appreciated!

**Comment by lonkelle** [comment]
@kibabyte Delta only shows detected controllers. It could have gotten stuck which a re-install (delete and install) should fix. Or ncontrol is still broadcasting that fake controller and Delta is picking it up (re-installing the tweak or removing it should work).

Let me know if either of those things don't work for you and I'll dig deeper if need be. 🤞🏼
