### ISSUE TITLE
google drive syncing bug

### ISSUE THREAD

**Issue by Kdog88** [rileytestut/Delta#195]
There's a possible bug with syncing multiple apple devices with the same google drive account....please see the attached files for the complete picture of the bug 
![IMG_0022](https://user-images.githubusercontent.com/49170700/188315778-733fb6fe-8b6a-420f-b72e-431caedd98f8.jpeg)
![Screenshot 2022-09-04 at 8 52 50 AM](https://user-images.githubusercontent.com/49170700/188315779-5a0930e9-9b4c-4c56-9507-9f9872e4d7b9.png)
![Screenshot 2022-09-04 at 8 55 16 AM](https://user-images.githubusercontent.com/49170700/188315780-81543b51-91db-4d9e-b4b2-1a8ef8ef4c35.png)
bug is fixed by deleting delta altogether and sideloading it with a fresh install.

i am just opening this issue just so riley and others know about it so that it can be possibly be fixed so that other don't have to struggle with this frustrating bug

**Comment by aaiezza** [comment]
While we're on the topic, does anyone know how to actually access Delta's data via your Google Account if you are syncing?
For some reason, I expected to be able to find in my Google Drive, but I cannot seem to find it there. Is there some other location it should be able to be located?

**Comment by Electrox3d** [comment]
I'm here because I ran into this too. I started on a new phone with a fresh install and had this same issue. I guess I could remove everything and try again. But yeah if it can be fixed via update that would be ideal. thx.

**Comment by Electrox3d** [comment]
> @rileytestut While we're on the topic, does anyone know how to actually access Delta's data via your Google Account if you are syncing? For some reason, I expected to be able to find in my Google Drive, but I cannot seem to find it there. Is there some other location it should be able to be located?

So as far as I know you can't get to the actual data, but you can see how much hidden app data is used by going to Drive settings, and selecting Manage Apps. Delta is listed there.

**Comment by Electrox3d** [comment]
> I'm here because I ran into this too. I started on a new phone with a fresh install and had this same issue. I guess I could remove everything and try again. But yeah if it can be fixed via update that would be ideal. thx.

After turning off and on google sync several times it finally started syncing but of course has conflicts with every game. Which is a pain. They warn you you'll have to manually resolve conflicts if you toggle syncing, and that's what i'm going through now. fortunately the data is found at least and is restoring one by one. (Wish there was a resolve all selection and choose "restore from cloud"). Thx.

**Comment by lonkelle** [comment]
@aaiezza There's no way to access the Google Drive Delta data. It uses an API that Google hides from users. The only thing you can do is delete it all from your Google Drive Settings on the web. 

I use Dropbox for this exact reason as I prefer access to the files myself.

**Comment by lonkelle** [comment]
@Kdog88 Did this error you ran into ever reoccur after your re-install?

**Comment by Kdog88** [comment]
I can't remember how I got it fixed but it's fixed now

**Comment by lonkelle** [comment]
Thanks for the update. Closing this for now. Anyone feel free to reopen it if this is still happening to them.
