### ISSUE TITLE
No sound output when launching games

### ISSUE THREAD

**Issue by mk8itra1n** [rileytestut/Delta#2]
Hey Riley, this is one of your beta testers running the copy of Delta beta 5 you sent us earlier on in the month. I've sideloaded the .ipa using Ext3nder on my jailbroken iPhone 7 Plus and restored my database folder. All of my games show up normally however upon booting up any game I get no sound. I've checked my ringer settings and flipped the switch on and off and nothing. Turned up the volume obviously still nothing. Tried plugging in headphones to see if it's just a bug with speaker output but no sound comes out of those either. Pretty strange. Any help would be appreciated. Thx!

**Comment by 11SoniCHunter87** [comment]
> Upgraded to an iPhone X on launch day and sideloaded Delta. Sound works great now so maybe it was a specific hardware/software bug for that device that will be fixed in the next beta.
