### ISSUE TITLE
App closing when adding rom

### ISSUE THREAD

**Issue by typeiionair** [rileytestut/Delta#202]
I am running Delta via installed IPA through TrollStore. I am on an iPad Pro M1 12.9” on 15.1. The interface loads when opened but when I click on the plus icon the app crashes and closes.

**Comment by mpacepa** [comment]
iPad Pro M1 11”, 15.4.1, same issue :(

**Comment by CubeBag** [comment]
I can reproduce the issue on iPad Air 3rd Generation on iOS 15.3.1 with Delta version 1.3.2. It seems to affect iPads when the app is installed through TrollStore. Interestingly, when I install the app normally through AltStore, it puts the app into iPhone mode (with the fullscreen button), but when I install it through TrollStore, it seems to _force_ the app into iPad mode. This sounds like it could be related.

Also, I tested Delta 1.4b3, and although the plus button crash is fixed, games still do not have controls.

Also, there is a workaround to adding games, but they are still not playable: games on the iPad are unable to automatically fetch artwork (only display the default Delta grey icon), and the controls do not appear at all.
![IMG_0034](https://user-images.githubusercontent.com/17459634/199915883-7e003b61-590c-49bf-9f25-1692860bcd7b.PNG)
![IMG_0035](https://user-images.githubusercontent.com/17459634/199915876-6ac96ba2-1f28-4687-87b6-79fa7872097a.PNG)
![IMG_0036](https://user-images.githubusercontent.com/17459634/199916405-9b7b49d7-95fb-485f-88e5-2ebfde002964.PNG)

**Comment by CubeBag** [comment]
I was curious, so I then tested it in the beta release (1.4b3), and it appears to be _entirely_ fixed. The plus button works, and the controls show up when the keyboard is disconnected fully.
