### ISSUE TITLE
Delta is not working properly in Mac Catalyst environment

### ISSUE THREAD

**Issue by amirsaam** [rileytestut/Delta#204]
Hey buddy!
Thanks for your awesome project.

We at [PlayCover](https://github.com/PlayCover/PlayCover) trying to run Delta, but we experience various problems like sounds not  working or controller is broken.

Can you please check and help us out about it?
Maybe you can pinpoint some of our issues.

We will be happy if you contribute to the project about your awesome Delta project.

Regards.

**Comment by amirsaam** [comment]
For the records, we have tested Delta in Sideloadly too.
Looks like Delta itself has some issues running in macOS envoirment.
We would love if you could address this behaviour from Delta.

**Comment by lonkelle** [comment]
I believe I know how to fix this. You're running this on Apple Silicon correct?

**Comment by amirsaam** [comment]
@lonkelle yes.
