### ISSUE TITLE
hi，delta crashes in ios 13.3.1

### ISSUE THREAD

**Issue by mishizhq** [rileytestut/Delta#226]
delta crashes in ios 13.3.1, I installed with personal signature and it crashes, not if installing with enterprise signature, this issue has been after delta 1.3 version, 1.2 and earlier does not appear，Please fix it，thank you！

**Comment by jceaser** [comment]
When migrating up to that version, did you have an error like:

`Build input file cannot be found: '/Users/thomascherry/Documents/src/others/Delta/Cores/GBADeltaCore/GBADeltaCore/Standard.deltamapping'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

**Comment by ChimeraGaming** [comment]
Upgrade to latest version
