### ISSUE TITLE
Cancel button not behaving

### ISSUE THREAD

**Issue by cmdcarini** [rileytestut/Delta#25]
This _may_ be expected behaviour, but it initially struck me as a bug, so here I am. When clicking `Riley Testut` under `Credits`, iOS displays a popup to open the Twitter app; hitting cancel, simply opens it in a browser. imo, I would've though `Cancel` would just not forward to Twitter at all. Feel free to close if this is expected behaviour and I'm just dumb.

**Comment by chickdan** [comment]
I initially thought the same thing, but the alert is regarding opening the Twitter app instead of opening in the in-app browser.
