### ISSUE TITLE
Unable to clone repo for manual build.

### ISSUE THREAD

**Issue by 53SWYj3cV8nKsSr** [rileytestut/Delta#29]
The `git clone` is using a ssh link and won't let me clone the repo. I was able to finally clone the repo by using the https link, but it seems like the submodule is also using ssh so I wasn't able to clone them. Just wondering but is this intention, do I have to use the AltStore to get the application cause I would rather personally build my own apps if possible.

**Comment by DanTheMan827** [comment]
Add your SSH public key into your github account
```
cat ~/.ssh/id_rsa.pub
```
