### ISSUE TITLE
Launch to the App Store worldwide per Apple’s new guidelines

### ISSUE THREAD

**Issue by upintheairsheep** [rileytestut/Delta#292]
Hello, Apple recently updated their guidelines, now permitting game emulators from downloading ROMs not in the application binary. Can you ask Apple to if it is now OK to launch Delta to the App Store, or wether a separate App Store edition needs to be implemented, to conform with the application sandboxing guideline or the definition of “downloading” by only offering a selection of Homebrew ROM games?

**Comment by upintheairsheep** [comment]
Update: A GB/GBC/GBA emulator was accepted onto the store, allowing to use custom ROMs, so Delta may finally go to it’s originally intended destination.

**Comment by AxolotlAccount** [comment]
I hope Delta gets released on App Store individually because AltStore will only be available in EU countries as a third-party provider. 

In Non-EU countries, the only way to use AltStore without jailbreak is still sideloading from a computer with a 7-day limit that needs to be refreshed using a computer and it is very unconventional for average user.

If iGBA is allowed on the App Store, Delta would probably be allowed on the App Store too.

**Comment by upintheairsheep** [comment]
Agree, I cannot move to an EU country.

**Comment by Proryanator** [comment]
100% would love this, this apo deserves to be on the app store now. I would gladly pay the developers a one time fee to use the app officially.

**Comment by Harada-z** [comment]
GBA模拟器已经上架App store
![微信图片_20240415113321](https://github.com/rileytestut/Delta/assets/59907133/83a925e4-febe-47f5-9c14-45323fbcb7c4)

**Comment by lxgr** [comment]
> It's good that you put that only you or people with explicit written permission can publish delta to the app store cause you be sitting on a potential money maker right now @rileytestut ;)

That restriction is not compatible with the GPL, though (see also https://github.com/rileytestut/Delta/issues/296).

**Comment by lucoel** [comment]
> Delta — the app that started it all — is available NOW in the App Store!
> Yes, you read that right: our long-rejected game emulator has been approved by Apple themselves 🍎
> If you live outside the EU, download now from the App Store — no DMA required https://apps.apple.com/app/delta-game-emulator/id1048524688

https://fosstodon.org/@altstore/112287558511134794

**Comment by Piipperi** [comment]
Why can't I get it in the EU from the App Store?

**Comment by TCB13** [comment]
> Why can't I get it in the EU from the App Store? I know you can get it from AltStore PAL but that's iPhone only and it costs a yearly subscription

It's called a d*k move. @rileytestut decided to show the middle finger to every European by not publishing the App into the EU stores - all in hopes to push his little AltStore.

@rileytestut did you think it's a bit bad to sidetrack and run over the people who actually forced Apple into allowing the AltStore in the first place? Get your priorities right.

**Comment by upintheairsheep** [comment]
At least he didn’t say to every non-EU resident to “go move to an EU
country” then pay the subscription.

**Comment by DominusExult** [comment]
And apparently the former "trick" to just use an US account is no longer working for US store apps. Seems the geo location check that Apple added in 17.4 works for that, too :(

**Comment by TCB13** [comment]
> And apparently the former "trick" to just use an US account is no longer working for US store apps. Seems the geo location check that Apple added in 17.4 works for that, too :(

Maybe you can just ask @rileytestut to be a decent person and click on the toggle to make the app available in the EU. Thank you.

**Comment by gh0sti** [comment]
its on the store this can be closed.

**Comment by TCB13** [comment]
> its on the store this can be closed.

NOT in the EU.

**Comment by gh0sti** [comment]
> > its on the store this can be closed.
> 
> NOT worldwide, NOT in the EU as Delta is only available on the US store. That's the new problem.

EU is available via altstore appstore

**Comment by TCB13** [comment]
> > > its on the store this can be closed.
> > 
> > 
> > NOT worldwide, NOT in the EU as Delta is only available on the US store. That's the new problem.
> 
> EU is available via altstore appstore

Yes and for that you've to pay a subscription. Why is it available on the Apple's App Store for free in the US and in Europe you gotta pay?

**Comment by DominusExult** [comment]
> > > its on the store this can be closed.
> 
> > 
> 
> > NOT worldwide, NOT in the EU as Delta is only available on the US store. That's the new problem.
> 
> 
> 
> EU is available via altstore appstore

As per the issue request it's about the Apple AppStore, not the AltStore, so no, issue is not fixed.

**Comment by upintheairsheep** [comment]
Closed, got it downloaded and on the store for everyone, but EU users need to pay for AltStore PAL. Feel free to open another issue to get it on EU as well, I don’t live in an EU country so my issue is solved.

**Comment by TCB13** [comment]
Well, the title of the issues says "Launch to the App Store worldwide". EU is part of "worldwide" last time I checked.

**Comment by Proryanator** [comment]
@rileytestut congratulations! Well deserved to have it officially on the app store.
