### ISSUE TITLE
Delta Error Installing With ReProVision

### ISSUE THREAD

**Issue by gatekeeper1122** [rileytestut/Delta#33]
Heres a picture that explains it all idk what else todo at this point
![LbHgwKo](https://user-images.githubusercontent.com/16184353/66953354-953b8580-f01b-11e9-8c4f-0f1ca384d02b.jpg)

**Comment by CatsLover2006** [comment]
I don’t have this issue. Try the 1.1 iOS 12.0+ build, worked for me on iOS 12.1.2 on a iPhone 6s
