### ISSUE TITLE
Will Delta Bring Back The DSI Bios?

### ISSUE THREAD

**Issue by GFLJS2100** [rileytestut/Delta#340]
The DSI Bios Was There In The Beta Versions, but in latest versions, it removed the dsi bios, Can Delta Bring Back The DSI Bios In The Latest Versions?

**Comment by ZachieBlade** [comment]
Probably bc it's illegal to distribute BIOS files. Dump your own, or find it yourself.

**Comment by HunterBoy344** [comment]
> Probably bc it's illegal to distribute BIOS files. Dump your own, or find it yourself.

I'm pretty sure he's talking about the feature to import DSi BIOS files, not the actual files themselves.
