### ISSUE TITLE
NES Game Genie will not accept more than six characters for the code. 

### ISSUE THREAD

**Issue by jasondill** [rileytestut/Delta#35]
The Code format is currently locked to 6 characters. We're unable to use 8 character game genie codes.

**Comment by elmstreetvictim** [comment]
Upvoted. Experiencing this. Reported on reddit and confirmed by a mod I believe, who said he could get in touch with the creator.

**Comment by JoelStickney** [comment]
I was told @rileytestut fixed this at one point but the fix got reverted during an update.

**Comment by elmstreetvictim** [comment]
What is the likelihood of finding the diffs and merging in the previous handling code, for the next update of Delta beta

**Comment by JoelStickney** [comment]
I don't think it would need to be as complicated as needing to find the old code. It's just a condition that restricts NES codes to exactly 6 characters. So all that needs to happen is that conditional he'll probably add an "OR == 8" next to the 8 characters for Game Genie codes. I'd bank (#nesprogrammingjoke) on this shipping with the next update. Riley didn't confirm he was going to fix it, but I bugged him a lot about fixing the blank screen NES bug so I think he *may* add the extra conditional to get 8 codes working. 🤞

**Comment by ericlewis** [comment]
from what I can tell, this should be resolved in 1.2, it appears you can type more that 6 chars.

**Comment by jasondill** [comment]
It’s fixed. So I’m closing this issue.
