### ISSUE TITLE
Delete Rom Files from Drive

### ISSUE THREAD

**Issue by Carpi2001** [rileytestut/Delta#38]
I can't seem to delete the rom files from drive that have been synced. I had selected to not upload the rom, but once it uploads the first time, the file doesn't delete.  Is there any way to remove it.

**Comment by tgwaste** [comment]
Hello @Carpi2001 
- Open a browser
- Go to your google drive
- Click Settings
- Under Settings click Managed Apps
- Find Delta and under Options click **Delete Hidden App Data**
