### ISSUE TITLE
Sound issues on apps store

### ISSUE THREAD

**Issue by kevinW0W** [rileytestut/Delta#383]
Is was from app store cuz my delta won’t play the sound when I was playing SM64. Pls update to fix bugs.
Thx

**Comment by kevinW0W** [comment]
And also I try the to turn off and on the respect slient mode. But still won’t work. </big>**Is their anyways to fix this bugs?**<big>

**Comment by kevinW0W** [comment]
Nvm it was a sound recognition. Cuz i turn off and that how the sound doesn't work. ![image](https://github.com/rileytestut/Delta/assets/152757721/aa6e3117-3f7e-4abc-8dfa-f0dcd88574c7)

**Comment by jthomp** [comment]
I also had Sound Recognition turned off. Turned it back on but still no sound. Using iOS 18 beta 1 and the App Store version.
