### ISSUE TITLE
Flipping to Landscape mode crashes entire app for N64 and DS

### ISSUE THREAD

**Issue by 904funny** [rileytestut/Delta#439]
This has been happening consistently since last update. It just freezes like this. PLEASE ADDRESS!
![IMG_8420](https://github.com/user-attachments/assets/1183ed0f-7d31-4c60-b2d4-2b81bc4cb6bc)
![IMG_8421](https://github.com/user-attachments/assets/c4c74444-6484-4695-bfe3-a98dea8c3a84)

**Comment by Megvmin** [comment]
Having the same issue as well, not only on ds and n64, but everything.

**Comment by 904funny** [comment]
> Having the same issue as well, not only on ds and n64, but everything.

Strangely, SNES works fine.
