### ISSUE TITLE
Dropbox Access for App Only?

### ISSUE THREAD

**Issue by stanton119** [rileytestut/Delta#47]
Thanks for a great app!
When syncing with Dropbox it lists Delta as requiring full dropbox access. GBA4iOS required the app folder only. Is there any reason why Delta requires full read/write access to dropbox outside of its own app folder?

**Comment by cameronetchart** [comment]
Came here searching for this exact request. Right now the app requires us to grant full access to everything in Dropbox, but Dropbox supports app folders, where the app has full access only to a special app folder. I can’t justify granting full/full Dropbox access from a privacy and security perspective, but an app folder solves that whole issue. Thank you!!

**Comment by dlevi309** [comment]
> Came here searching for this exact request. Right now the app requires us to grant full access to everything in Dropbox, but Dropbox supports app folders, where the app has full access only to a special app folder. I can’t justify granting full/full Dropbox access from a privacy and security perspective, but an app folder solves that whole issue. Thank you!!

It only gives access to a shared folder named “delta emulator”, not your entire account.

**Comment by cameronetchart** [comment]
> > Came here searching for this exact request. Right now the app requires us to grant full access to everything in Dropbox, but Dropbox supports app folders, where the app has full access only to a special app folder. I can’t justify granting full/full Dropbox access from a privacy and security perspective, but an app folder solves that whole issue. Thank you!!
> 
> It only gives access to a shared folder named “delta emulator”, not your entire account. 

That doesn’t appear to be true according to the screen my Dropbox app gives me when I try to link. When apps use the Dropbox “app folder” feature I recall seeing a different message. 

https://help.dropbox.com/installs-integrations/third-party/third-party-apps

![image](https://user-images.githubusercontent.com/6248778/82634373-89282f80-9bcb-11ea-9c82-02bc78101b42.jpeg)

**Comment by dlevi309** [comment]
That’s the common request when using dropbox’s api, and even so, that doesn’t actually specify anything related to “full write access to my entire Dropbox” it’s asking if it has permission to a). create a folder, b). Upload files to that folder on your behalf. It’s the standard permission request with dropbox’s api. Even once you delete that shared folder, the access is revoked.
