### ISSUE TITLE
Documentation for Adding Additional Cores?

### ISSUE THREAD

**Issue by ianclawson** [rileytestut/Delta#48]
Hopefully this is the right place to ask, otherwise I'm happy to close this and ask elsewhere!

I'd love to explore implementing additional system cores, but outside of looking through the code I'm not sure where to start. I see some of the more obvious areas (like adding to the enum in Systems.swift, adding the controller skin/mapping, etc) but I'm sure there's a lot more smaller areas I'm not seeing, as well as everything that the cores need to expose to DeltaCore.

It would be super helpful to create some high-level documentation about the major pieces that need to be included, the files that those pieces are located in for reference, as well as any advice/learnings for some of the lower-level areas that you're willing to share. I'm definitely more of a high-level guy but want to explore and learn more of the lower-level stuff 🙂 

Thanks!

**Comment by MaxHasADHD** [comment]
@ianclawson did you find documentation? why is this closed? I'd love this as well.

**Comment by ianclawson** [comment]
@MaxHasADHD In the end I closed because I thought to myself:

1. Delta/DeltaCore is still evolving, so the spec is prone to change in the future
2. the readme for Delta still the sleep-deprived placeholder that was thrown up when the project first went live, so I'd wager there are more pressing needs and priorities than developer documentation
3. there perhaps isn't enough known developer interest/demand to justify time spent into providing documentation
4. after playing with adding my own cores, it's not an exact science; the DeltaCore spec is pretty consistent of course, but every core library I've seen varies wildly on how to get audio/video, send inputs, etc.

While I did not find documentation, I _sorta_ found enough info that gets me by for now:

- Looking through the existing Core repos you can see patterns in the files available:
1. They are frameworks (these days static I believe but they were once dynamic)
2. A Swift core struct that conforms to `DeltaCoreProtocol` which exposes the functionality to projects importing the framework. This `DeltaCoreProtocol` exposes the `GameType`,  `Input.Type`, `EmulatorBridging`, `audioFormat`/`videoFormat` and other files/types that DeltaCore need to hook into the core. You can refer to each individual core for examples
3. A Objective-C/C++ Emulator Bridge that conforms to `DLTAEmulatorBridging` which exposes the runtime methods/callbacks needed for DeltaCore to get audio/video from and send controller inputs to the core. It is in this file that all of the interfacing to the actual (usually c++) equation core happens. The `DLTAEmulatorBridging` protocol will require you implement the base functions needed for the audio/video/inputting/saving/etc. to happen. You can refer to each individual core for examples
4. Controller Skins. There's more documentation available for this area that you can find here: https://github.com/rileytestut/DeltaCore/wiki/Skins
- If you look at any of the existing Core repos and look at their commit history, the first commits are pretty well isolated to implementing basic versions of the major pieces of functionality required by `DeltaCoreProtocol` and `DLTAEmulatorBridging`. [GBCDeltaCore](https://github.com/rileytestut/GBCDeltaCore/commits/master) for example has commits titled `Adds basic implementation of required DeltaCore functionality` and `Implements basic emulation + video rendering`, so by looking though those you can start to see some basic patterns
- This all of course if subject to change as Delta evolves

Interfacing with the end cores them selves is the hardest part IMO. Depending on the core documentation is sparsely available, and getting everything to link and compile correctly is a pain for someone like me with very limited c++ experience. I've learned a lot about header/framework/user search paths, static libraries, and more since I began this journey, but there's still so much that I just don't know yet.

Hope that helps!
