### ISSUE TITLE
Bind some buttons to touch controls with a limited controller

### ISSUE THREAD

**Issue by cgarst** [rileytestut/Delta#58]
There are some scenarios where some controllers do not have enough buttons to function with all of the required binds. Adding the ability to bind these extra buttons on-screen would make it workable.

For example, using the 8bitdo SN30 with SNES games. This is a copy of the SNES controller. After pairing it in iOS 13 using the [Switch Controls](https://www.reddit.com/r/8bitdo/comments/dk8p0x/how_to_pair_an_8bitdo_controller_with_iosipados/) trick, SN30 in Delta defaults to having Start bound to Menu, and the Select button isn't recognized at all for some reason. In this example, no matter how you assign the controls you're missing two essential buttons (by default, Start and Select). I would prefer to bind Start to Start and have Select and Menu appear as a touch control.

**Comment by shanegillio** [comment]
Hi there! A similar post with this suggestion has been marked, so closing this as a duplicate
