### ISSUE TITLE
'Revision.h' file not found when trying to compile "develop"

### ISSUE THREAD

**Issue by benjamincrozat** [rileytestut/Delta#59]
Hello,

`'Revision.h' file not found` when trying to compile the `develop` branch. I pulled the last changes as well as for the submodules. What am I doing wrong?

**Comment by benjamincrozat** [comment]
Found a script that generates the missing file.

```bash
sh Cores/N64DeltaCore/Mupen64Plus/GLideN64/src/getRevision.sh
```

**Comment by dlevi309** [comment]
Hi, I wish I’d seen this earlier to comment, I’m not sure exactly when but at some point around the cores transition to pod files, the Revision.h never seemed included. I’d just been re-adding a copy of the revision header from a couple months ago, but for anyone seeing this who wants to just input the header manually for a quick build, this should be sufficient;

#define PLUGIN_REVISION ""
#define PLUGIN_REVISION_W L""

 ^ input that into a file titled “Revision.h” and drop it into this path ~/Delta/Cores/N64DeltaCore/Mupen64Plus/GLideN64/src/Revision.h

**Comment by benjamincrozat** [comment]
@dlevi309 Not sure if that's because I changed constants values by an empty one, but compilation now works. Thanks. :)

**Comment by dlevi309** [comment]
@benjamincrozat I’m glad I could help, hope you enjoy!
