### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by panchokoster** [rileytestut/Delta#63]
Hi!
I was trying to compile Delta from source, however I couldn't download the sources properly.

In the README it should say:
git clone https://github.com/rileytestut/Delta.git

The current text, 
git clone git@github.com:rileytestut/Delta.git
is giving a "Permission denied (publickey)."

This also, happens to most of the submodules when running
git submodule update --init --recursive

**Comment by neralas** [comment]
I have the same problem with submodules. "Permission denied (publickey)."

**Comment by dlevi309** [comment]
Try checking out the dev branch with this command:

git clone -b develop https://github.com/rileytestut/Delta.git --recurse-submodules

**Comment by ericlewis** [comment]
Thanks @dlevi309 closing this for now.
