### ISSUE TITLE
Problems Syncing

### ISSUE THREAD

**Issue by tgwaste** [rileytestut/Delta#7]
1> There is no option to Sync to iCloud.  I would think this would be the default especially because its creating a Delta folder in iCloud thats empty.
2> Syncing to Google Drive doesn't work at all.  It says It's doing it but nothing shows up in my Drive folder.
3> Syncing to DropBox seems to require access to all files.  YIKES.
4> Saving data to Files does nothing.

**Comment by tgwaste** [comment]
This doesnt seem right
![Screen Shot 2019-09-28 at 6 04 49 PM](https://user-images.githubusercontent.com/690918/65824240-93e81b80-e21a-11e9-9563-962875525274.png)

**Comment by ianclawson** [comment]
It's the way Google Drive handles app specific data: https://developers.google.com/drive/api/v3/appdata

Looks to be more of an implementation detail than a bug.

**Comment by tgwaste** [comment]
It would be nice to be able to easily access and backup the data that the application is syncing.
But I'll close this for now.
