### ISSUE TITLE
Features Request: RetroAchievements

### ISSUE THREAD

**Issue by MohandL3G** [rileytestut/Delta#71]
I hope that you can add the option to link RetroAchievements and win Achievements, I really like it I have ton of achievements, and I want to be able to play with Delta on my iPad, as RetroArch doesn't work, and Delta looks more better, I tried to Copy my saves between RAProject64 and Delta and it works, So my saves are synced but what I want is to win Achievements from both my PC and my iPad, and Thanks in Advance.

**Comment by shanegillio** [comment]
A few people have asked for this, and I have it marked. Closing as a duplicate
