### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by b8magic** [rileytestut/Delta#73]
Will ever multiplayer for ds be available? For example for pokemon games like platinum or soul silver, it would be great to be able to trade pokemon or battle some friends (maybe with some wifi, bluetooth, local, or other connection I don't know)

thank you really much in advance

**Comment by jawshoeadan** [comment]
It is being worked on, but there is no ETA. It is a planned feature for the future which you can track on the [Delta Trello board](https://trello.com/b/P6YH3nl9/delta-emulator-roadmap)

**Comment by LiterallyUnknown** [comment]
melonDS has native local multiplayer support, might wanna check that out.

**Comment by shanegillio** [comment]
local multiplayer now in beta!
