### ISSUE TITLE
on-screen controller setting doesn’t stick (reverts to Keyboard)

### ISSUE THREAD

**Issue by chinarut** [rileytestut/Delta#74]
I’m on an iPadPro (2018) (iOS 13.6) and for some reason the controller setting doesn’t stick.   It resets to “Keyboard” every time.  I need to go into settings and select my iOS device so I can use the on screen controller.

![IMG_0494](https://user-images.githubusercontent.com/6845061/90712377-bb433f00-e257-11ea-918c-bbade2d3e025.png)

**Comment by shanegillio** [comment]
Are you still having issues?

**Comment by chinarut** [comment]
hey sorry it's taken so long to circle around.  thanks for checking in.

I since moved onto Batocera so I'll close this issue for now.
