### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by DanTheMan827** [rileytestut/Delta#77]
Are you going to attempt to submit Delta to the App Store?

iDOS 2 had an update approved that turned it into a fully functional DOS emulator able to load any exe instead of just something bundled with a couple shareware titles, so you could use that as a reason why Delta should be approved if they were to reject it.

Apple has stated they treat every developer equally, so if they reject Delta but not iDOS 2 there goes that argument.

https://github.com/litchie/dospad/issues/90

**Comment by ericlewis** [comment]
It is very unlikely this will happen as it is executing downloaded 3rd party code.

**Comment by DanTheMan827** [comment]
IDOS 2 also executes external code, it’s an emulator just like delta, it just emulates a different system
