### ISSUE TITLE
Can't import NDS ROMs from Files on latest public Delta release

### ISSUE THREAD

**Issue by ghost** [rileytestut/Delta#80]
When it opens the files app, all my NDS ROMs are a dark color, and I can't select them -- is NDS not supported yet in the public release or something?

**Comment by LiterallyUnknown** [comment]
Yes. NDS **_game_** emulation is not supported yet in the Delta Public Release. However, NDS emulation was still left in, but because of some changes from Beta and Public, you cannot import .nds games from Files to Delta. You could, however, emulate the Home Screen with melonDS.

**Comment by unbeatable-101** [comment]
Choose DeSmuME from core settings, the. Switch to melonDS

**Comment by hwittenborn** [comment]
I’d use melonDS, but I don’t got a DS anymore to get the necessary files — I’m pretty sure it’s piracy, but if not, is there anywhere I can download them?

**Comment by unbeatable-101** [comment]
[NDS Firmware & BIOs.zip](https://github.com/rileytestut/Delta/files/5521099/NDS.Firmware.BIOs.zip)

I wouldn't say it is piracy if you owned it

**Comment by LiterallyUnknown** [comment]
bios files fall under copyright laws also. even if you say it isnt piracy, it is piracy.
oh also you could browse the develop tree if you want to if you want to get a beta version of delta

**Comment by unbeatable-101** [comment]
> bios files fall under copyright laws also. even if you say it isnt piracy, it is piracy.

It’s literally the same as if I got it off my own device

**Comment by hwittenborn** [comment]
> > bios files fall under copyright laws also. even if you say it isnt piracy, it is piracy.
> 
> It’s literally the same as if I got it off my own device

I don’t have a DS anymore, so that’s sadly out of the question.

> oh also you could browse the develop tree if you want to if you want to get a beta version of delta

I need to compile to do that, right? Sadly don’t got a Mac 😔

**Comment by unbeatable-101** [comment]
> I don’t have a DS anymore, so that’s sadly out of the question.

I provided the files, I was just saying using the files is the same as getting them off your own device

**Comment by hwittenborn** [comment]
> I provided the files, I was just saying using the files is the same as getting them off your own device

Yeah yeah, that all makes sense.

Shocked the BIOS can just be provided like that though — would’ve thought that would’ve been comparable to a ROM or so.

Anyhow that’s getting into a whole other area, I’m gonna leave it at that.

**Comment by muyinliu** [comment]
> [NDS Firmware & BIOs.zip](https://github.com/rileytestut/Delta/files/5521099/NDS.Firmware.BIOs.zip)
> 
> I wouldn't say it is piracy if you owned it

Same files from page https://emulation.gametechwiki.com/index.php/Emulator_files#Nintendo_DS_.2F_DSi , click the link `DS BIOS files and firmware` to download.

Thanks.
