### ISSUE TITLE
BUG: SNES sound crackling issue

### ISSUE THREAD

**Issue by cbyeh** [rileytestut/Delta#89]
Fixed after loading or saving a save state so it may be a syncing issue.

See:
https://www.reddit.com/r/Delta_Emulator/comments/dxbf3p/sound_crackling_issue/
https://www.reddit.com/r/Delta_Emulator/comments/dh3rcd/anyone_figure_out_a_fix_for_the_crackling_sound/
Crunchy audio when playing SNES games? : Delta_Emulator

**Comment by ianclawson** [comment]
There was very recently (yesterday) an alpha pushed that resolves this issue! I expect that a beta and eventual release will follow in the coming days/weeks 👏
