### ISSUE TITLE
Can’t import .nds on latest public build

### ISSUE THREAD

**Issue by wg481** [rileytestut/Delta#95]
I have melonDS set up and everything, but I can’t import a nds file. Is there a different file format or is this currently unsupported?
I attached a screenshot for further info.
![E056B686-AE83-4D2E-9F02-428D4B85A94C](https://user-images.githubusercontent.com/77253779/104140764-d8dc8680-5367-11eb-81ca-470d43a85267.jpeg)

**Comment by Jdewi12** [comment]
I think I had the same issue and worked around it by switching to the desmume core before importing.

**Comment by CatsLover2006** [comment]
This might be one of the Patreon "issues", where it needs the Patreon stuff.
