### ISSUE TITLE
JIT post IOS 14.4 Beta 2

### ISSUE THREAD

**Issue by ArturoGuerra** [rileytestut/Delta#97]
JIT is nonfunctional on IOS 14.4 beta 2 and it appears it will stay that way due to the fact code signing is disabled when the application is attached to a debugger.
 
Original source of information about this:
https://github.com/utmapp/UTM/issues/2271#issuecomment-761725159

**Comment by ArturoGuerra** [comment]
Appears JIT has been disabled https://github.com/rileytestut/Delta/commit/1871f69acadce892a9248c20e0d06cc9ed9fa948

**Comment by hmzbg** [comment]
https://github.com/rileytestut/Delta/issues/97#issuecomment-763394197
